substitutions:
  _PROJECT: sdkorg
  _REGION: us-central1
  _REPO: udaanpath-repo
  _IMAGE: udaanpath
  _SERVICE: udaanpath-web

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # ===============================
  # 1️⃣ Build Docker image
  # ===============================
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/${_IMAGE}:${SHORT_SHA}",
        "-t",
        "${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/${_IMAGE}:latest",
        "."
      ]

  # ===============================
  # 2️⃣ Push image
  # ===============================
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/${_IMAGE}:${SHORT_SHA}"
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/${_IMAGE}:latest"
      ]

  # ===============================
  # 3️⃣ Deploy to Cloud Run (WITH ENV VARS)
  # ===============================
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "${_SERVICE}",

        "--image",
        "${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/${_IMAGE}:${SHORT_SHA}",

        "--region", "${_REGION}",
        "--platform", "managed",
        "--allow-unauthenticated",
        "--port", "3000",

        "--set-env-vars",
        "NODE_ENV=production",

        "--set-env-vars",
        "INTERNAL_API_BASE_URL=https://udaanpath.com",

        "--set-env-vars",
        "INTERNAL_API_TOKEN=internal-master-koendfewn23n23n23n23n23n23",

        "--set-env-vars",
        "EXTERNAL_AUTH_BASE_URL=https://udaanpath-web-333176137178.us-central1.run.app/api",

        "--set-env-vars",
        "EXTERNAL_AUTH_MASTER_TOKEN=master-feb94420ff1444c78697cee82c6a4b7d",

        "--set-env-vars",
        "DB_HOST=itsiksha-db.c7k2cwoo4963.ap-south-1.rds.amazonaws.com",

        "--set-env-vars",
        "DB_USER=admin",

        "--set-env-vars",
        "DB_PASS=SdKVande007*AWSSQL25",

        "--set-env-vars",
        "DB_NAME=itsiksha",

        "--set-env-vars",
        "DB_PORT=3306",

        "--set-env-vars",
        "NEXT_PUBLIC_ADSENSE_CLIENT_ID=ca-pub-5566458360910453",

        "--set-env-vars",
        "NEXT_PUBLIC_GA_ID=G-7TZ5S25XCX",

        "--set-env-vars",
        "NEXT_PUBLIC_GTM_ID=GTM-57X2R4PM",

        # ✅ Newly added (missing) variables
        "--set-env-vars",
        "STUDENT_EXAM_API_TOKEN=internal-master-koenduy65ywt45t54rtgt56567rthrt",

        "--set-env-vars",
        "UEAS_TOKEN_BYTES=32",

        "--set-env-vars",
        "UEAS_BCRYPT_ROUNDS=10",

         # ===============================
        # 🔹 Cloudinary (Image CDN)
        # ===============================
        "--set-env-vars",
        "CLOUDINARY_CLOUD_NAME=domixqd2u",

        "--set-env-vars",
        "CLOUDINARY_API_KEY=922443151119374",

        "--set-env-vars",
        "CLOUDINARY_API_SECRET=LNhTE98f06gYNy87KMpuZmtdqSU",

        # ===============================
        # 🔹 AWS SES SMTP (already using SES)
        # ===============================
        "--set-env-vars",
        "SMTP_HOST=email-smtp.ap-south-1.amazonaws.com",

        "--set-env-vars",
        "SMTP_PORT=587",

        "--set-env-vars",
        "SMTP_SECURE=false",

        "--set-env-vars",
        "SMTP_USER=AKIA4SDNV2C3ZZTUZV64",

        "--set-env-vars",
        "SMTP_PASS=BN7h6T2qPqYFQP4L8kwkNYXx/HLbXHK81k83zfy7V/CO",

        "--set-env-vars",
        "MAIL_FROM_NAME=UdaanPath",

        "--set-env-vars",
        "MAIL_FROM_EMAIL=info@udaanpath.com"

      ]

images:
  - "${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/${_IMAGE}:${SHORT_SHA}"
  - "${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/${_IMAGE}:latest"
